#ifndef EXTRACT_STATE_H
#define EXTRACT_STATE_H

/**
 *  extract.erofs result
 */
enum extract_result {
	RET_EXTRACT_DONE = 0,
	RET_EXTRACT_CONFIG_DONE = 1,
	RET_EXTRACT_CONFIG_FAIL,
	RET_EXTRACT_INIT_FAIL,
	RET_EXTRACT_INIT_NODE_FAIL,
	RET_EXTRACT_OUTDIR_ROOT,
	RET_EXTRACT_CREATE_DIR_FAIL,
	RET_EXTRACT_CREATE_FILE_FAIL,
	RET_EXTRACT_THREAD_NUM_ERROR,
	RET_EXTRACT_FAIL_SKIP,
	RET_EXTRACT_FAIL_EXIT,
};
#endif // EXTRACT_STATE_H
